### ISSUE TITLE
cant add a = sign in the oauth_callback 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chrismessina/oauth#122]
```
What steps will reproduce the problem?
Fatal error: Uncaught exception 'EpiOAuthUnauthorizedException' with
message 'Failed to validate oauth signature and token' in
F:\wamp\www\wp-content\plugins\mytwitterapp\classes\EpiOAuth.php:272 Stack
trace: #0
F:\wamp\www\wp-content\plugins\mytwitterapp\classes\EpiOAuth.php(251):
EpiOAuthException::raise('Failed to valid...', 401) #1
F:\wamp\www\wp-content\plugins\mytwitterapp\classes\EpiOAuth.php(32):
EpiOAuthResponse->__get('oauth_token') #2
F:\wamp\www\wp-content\plugins\mytwitterapp\classes\EasyTwitter.php(75):
EpiOAuth->getAuthorizationUrl(NULL, Array) #3
F:\wamp\www\wp-content\plugins\mytwitterapp\classes\EasyTwitter.php(38):
EasyTwitter->getAuthUrl(Array) #4
F:\wamp\www\wp-content\plugins\mytwitterapp\templates\settings_admin_template.ph
p(95):
EasyTwitter->auth(Array) #5
F:\wamp\www\wp-content\plugins\mytwitterapp\mytwitterapp.php(85):
mytwitterapp_settings() #6 F:\wamp\www\wp-includes\plugin.php(339):
get_mytwitterapp_settings() #7 F:\wamp\www\wp-admin\admin.php(91):
do_action('') #8 {main} thrown in
F:\wamp\www\wp-content\plugins\mytwitterapp\classes\EpiOAuth.php on line 272

mine callbackurl on this error is : 
http://localhost/wp-admin/admin.php?page=mytwitterapp/mytwitterapp.php

but when i use this:
http://localhost/wp-admin/admin.php?page_mytwitterapp/mytwitterapp.php
it works flawlessly

so mine conclusion is therefore i cant use the = in the oauth_callback.

i tried the %3D but i cant get i working.
well i could write a rewrite rule in mine htaccess
but still i am wondering why this cant be done?

because if i enter the callback url in the twitter app it will work?

what i am doing wrong?

maybey someone could help me with this.

grts,

eaonflux
```

Original issue reported on code.google.com by `eaonf...@gmail.com` on 16 Sep 2009 at 12:39

**Comment by GoogleCodeExporter** [comment]
Original comment by `jmkrist...@gmail.com` on 29 May 2010 at 3:20
- Added labels: **Lib-PHP**

**Comment by GoogleCodeExporter** [comment]
```
EpiTwitter doesn't use OAuth.php so you should probably submit a support 
request to EpiTwitter issue tracker: 
https://github.com/jmathai/twitter-async/issues
```

Original comment by `4braham` on 24 Jan 2011 at 2:22

**Comment by GoogleCodeExporter** [comment]
Original comment by `morten.f...@gmail.com` on 29 Mar 2011 at 5:56
- Changed state: **Invalid**
